import type { Env, ItemRow } from './types';
import { escapeHtml } from './utils';
import { getReportItems } from './db';
import { pushDailyReport } from './telegram';
function beijingWindow(now=new Date()):{reportDate:string;start:string;end:string}{const shifted=new Date(now.getTime()+8*60*60*1000);const y=shifted.getUTCFullYear(),m=shifted.getUTCMonth(),d=shifted.getUTCDate();const endUtc=new Date(Date.UTC(y,m,d,4,0,0));const startUtc=new Date(endUtc.getTime()-24*60*60*1000);const reportDate=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;return{reportDate,start:startUtc.toISOString(),end:endUtc.toISOString()};}
function kindLabel(kind:string):string{return({free_credit:'免费额度',limited_offer:'限时优惠',price_drop:'降价',price_change:'价格变化',new_plan:'新套餐',other:'其他'}as Record<string,string>)[kind]||'其他';}
function itemCard(item:ItemRow&{source_name:string}):string{const status=item.verification_status==='official_confirmed'?'官方确认':item.verification_status==='cross_verified'?'交叉验证':'未核实';return `<article class="card"><div class="meta"><span>${escapeHtml(kindLabel(item.kind))}</span><span>${escapeHtml(status)}</span></div><h2>${escapeHtml(item.title)}</h2>${item.summary?`<p>${escapeHtml(item.summary.slice(0,900))}</p>`:''}<div class="foot"><span>${escapeHtml(item.source_name)}</span>${item.url?`<a href="${escapeHtml(item.url)}" rel="noopener noreferrer" target="_blank">原文</a>`:''}</div></article>`;}
function renderReport(reportDate:string,items:(ItemRow&{source_name:string})[]):string{const p2=items.filter(x=>x.priority==='P2'),p3=items.filter(x=>x.priority==='P3');return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI-Radar 日报 ${escapeHtml(reportDate)}</title><style>body{font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;max-width:860px;margin:0 auto;padding:24px;background:#f6f7f9;color:#171717}a{color:inherit}.top{margin-bottom:28px}.sub{color:#666}.section{margin:28px 0}.card{background:white;border:1px solid #e7e7e7;border-radius:14px;padding:18px;margin:12px 0}.card h2{font-size:18px;margin:10px 0}.card p{line-height:1.65;color:#333}.meta,.foot{display:flex;justify-content:space-between;gap:12px;color:#6b7280;font-size:13px}.empty{color:#777;padding:16px 0}@media(max-width:600px){body{padding:16px}.card{padding:15px}}</style></head><body><div class="top"><h1>AI-Radar 日报</h1><div class="sub">${escapeHtml(reportDate)} · 每日 12:30（北京时间）推送</div></div><section class="section"><h2>值得关注</h2>${p2.length?p2.map(itemCard).join(''):'<div class="empty">今天没有值得关注的信息。</div>'}</section><section class="section"><h2>其他线索</h2>${p3.length?p3.map(itemCard).join(''):'<div class="empty">今天没有其他线索。</div>'}</section></body></html>`;}
export async function generateDailyReport(env:Env,now=new Date()):Promise<{reportDate:string;itemCount:number;pushed:boolean}>{const w=beijingWindow(now);const items=await getReportItems(env.DB,w.start,w.end);const html=renderReport(w.reportDate,items);await env.DB.prepare(`INSERT INTO daily_reports(report_date,window_start,window_end,item_count,html,generated_at) VALUES(?1,?2,?3,?4,?5,CURRENT_TIMESTAMP) ON CONFLICT(report_date) DO UPDATE SET window_start=excluded.window_start,window_end=excluded.window_end,item_count=excluded.item_count,html=excluded.html,generated_at=CURRENT_TIMESTAMP`).bind(w.reportDate,w.start,w.end,items.length,html).run();const counts={p2:items.filter(x=>x.priority==='P2').length,p3:items.filter(x=>x.priority==='P3').length};const pushed=await pushDailyReport(env,w.reportDate,counts);if(pushed)await env.DB.prepare('UPDATE daily_reports SET telegram_pushed_at=CURRENT_TIMESTAMP WHERE report_date=?1').bind(w.reportDate).run();return{reportDate:w.reportDate,itemCount:items.length,pushed};}
export async function getDailyReport(env:Env,date:string):Promise<Response>{const row=await env.DB.prepare('SELECT html FROM daily_reports WHERE report_date=?1').bind(date).first<{html:string}>();if(!row)return new Response('Report not found',{status:404});return new Response(row.html,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'public, max-age=300'}});}
export async function getLatestReport(env:Env):Promise<Response>{const row=await env.DB.prepare('SELECT report_date FROM daily_reports ORDER BY report_date DESC LIMIT 1').first<{report_date:string}>();if(!row)return new Response('No report yet',{status:404});return new Response(null,{status:302,headers:{location:`/daily/${row.report_date}`}});}
